kind: Deployment
apiVersion: apps/v1
metadata:
  name: jenkins-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-app
  template:
    metadata:
      labels:
        app: jenkins-app
    spec:
      containers:
      - name: jenkins-app
        image: bitnami/jenkins:latest
        env:
          - name:  JENKINS_USERNAME
            value: test
        ports:
          - containerPort: 8080
            protocol: TCP
        resources: {}
        imagePullPolicy: IfNotPresent
          
