kind: Service
apiVersion: v1
metadata:
  name: jenkins
spec:
  type: NodePort
  ipFamilies:
    - IPv4
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: jenkins

