kind: Service
apiVersion: v1
metadata:
  name: jenkins-app
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    deployment: jenkins-app
status:
  loadBalancer: {}


