kind: Deployment
apiVersion: apps/v1
metadata:
  name: jenkins
  labels:
    DataClass: Medium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: bitnami/jenkins:latest
        env:
          - name:  JENKINS_USERNAME
            value: test
        ports:
          - name: http
            containerPort: 8080
          
